### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by tnagorra** [eoglethorpe/deeper#25]
Appears randomly on export page after a certain while.
![pasted image at 2017_09_26 10_01 pm](https://user-images.githubusercontent.com/4928045/30872000-63853cc8-a308-11e7-8d4f-42fbca7d9290.png)

![image](https://user-images.githubusercontent.com/4928045/30872804-088889bc-a30b-11e7-8b24-7ea47447f33e.png)

**Comment by eoglethorpe** [comment]
@tnagorra could you reference the commit that fixes this?

**Comment by tnagorra** [comment]
The problem was caused due to a bug in the react-store repository. The merge request which solves the issue is https://gitlab.com/toggle-corp/react-store/merge_requests/5

**Comment by eoglethorpe** [comment]
+1
